### ISSUE TITLE
dump

### ISSUE THREAD

**Issue by luisdemarchi** [jazzband/django-cities-light#151]
I can not dump the database. I'm using the latest version of Python and Django.

```
manage.py@projectX-webservice > cities_light_fixtures dump

bash -cl "/Volumes/MacHD/Users/Git/projectX-webservice/.env/bin/python /Applications/PyCharm.app/Contents/helpers/pycharm/django_manage.py cities_light_fixtures dump /Volumes/MacHD/Users/Git/projectX-webservice"
Using project.settings.development
Using DEVELOPMENT environment...
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pycharm/django_manage.py", line 41, in <module>
    run_module(manage_file, None, '__main__', True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Volumes/MacHD/Users/Git/projectX-webservice/manage.py", line 24, in <module>
    execute_from_command_line(sys.argv)
  File "/Volumes/MacHD/Users/Git/projectX-webservice/.env/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/Volumes/MacHD/Users/Git/projectX-webservice/.env/lib/python3.6/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Volumes/MacHD/Users/Git/projectX-webservice/.env/lib/python3.6/site-packages/django/core/management/__init__.py", line 205, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/Volumes/MacHD/Users/Git/projectX-webservice/.env/lib/python3.6/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/Volumes/MacHD/Users/Git/projectX-webservice/.env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Volumes/MacHD/Users/Git/projectX-webservice/.env/lib/python3.6/site-packages/cities_light/management/commands/cities_light_fixtures.py", line 23, in <module>
    class Command(BaseCommand):
  File "/Volumes/MacHD/Users/Git/projectX-webservice/.env/lib/python3.6/site-packages/cities_light/management/commands/cities_light_fixtures.py", line 53, in Command
    option_list = BaseCommand.option_list + (
AttributeError: type object 'BaseCommand' has no attribute 'option_list'
```

**Comment by max-arnold** [comment]
Please try the latest version from git master branch.

**Comment by jayvdb** [comment]
Fixed long ago.
