### ISSUE TITLE
Error after installing

### ISSUE THREAD

**Issue by mmandrille** [jazzband/django-cities-light#199]
https://github.com/yourlabs/django-cities-light/blob/88b897023f5cc7a0d76adaaf7e36343917ea698b/cities_light/settings.py#L142

python3 manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mmandrille/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/mmandrille/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/mmandrille/.local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mmandrille/.local/lib/python3.6/site-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/home/mmandrille/.local/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/dist-packages/cities_light/__init__.py", line 3, in <module>
    from .settings import *
  File "/usr/local/lib/python3.6/dist-packages/cities_light/settings.py", line 142, in <module>
    if 'mysql' in database['ENGINE'].lower():
KeyError: 'ENGINE'

**Comment by bomba1990** [comment]
@mmandrille This issue was fixed on this commit https://github.com/jazzband/django-cities-light/commit/6f349126c1fc173bb2e89fca084a352fb55d0628#diff-6d10bfb9f81cbe9c0843416ad5d3003f
