### ISSUE TITLE
Failing to populate db.

### ISSUE THREAD

**Issue by iogf** [jazzband/django-cities-light#219]
It seems it hangs.

~~~
(shiva) [tau@archlinux shiva-code]$ ./manage.py cities_light --progress
Assuming local download is up to date for http://download.geonames.org/export/dump/countryInfo.txt
RAM used: 38 MB Time:  0:00:00 Done: 100%|##########################################################################################|
Assuming local download is up to date for http://download.geonames.org/export/dump/admin1CodesASCII.txt
RAM used: 39 MB Time:  0:00:00 Done: 100%|##########################################################################################|
Assuming local download is up to date for http://download.geonames.org/export/dump/admin2Codes.txt
RAM used: 40 MB Time:  0:00:08 Done: 100%|##########################################################################################|
Assuming local download is up to date for http://download.geonames.org/export/dump/cities15000.zip
RAM used: 40 MB Time:  0:00:24 Done: 100%|##########################################################################################|


~~~

I have my app model as:

~~~
    country = models.ForeignKey(Country, on_delete=models.CASCADE, default=None)
    city = models.ForeignKey(City, on_delete=models.CASCADE, default=None)

~~~

Settings.py

~~~
CITIES_LIGHT_TRANSLATION_LANGUAGES = ['en']
CITIES_LIGHT_INCLUDE_COUNTRIES = ['FR']

~~~

It fails for india too.

~~~
shiva) [tau@archlinux shiva-code]$ ./manage.py cities_light --progress
Assuming local download is up to date for http://download.geonames.org/export/dump/countryInfo.txt
RAM used: 38 MB Time:  0:00:00 Done: 100%|##########################################################################################|
Assuming local download is up to date for http://download.geonames.org/export/dump/admin1CodesASCII.txt
RAM used: 39 MB Time:  0:00:00 Done: 100%|##########################################################################################|
Assuming local download is up to date for http://download.geonames.org/export/dump/admin2Codes.txt
RAM used: 40 MB Time:  0:00:25 Done: 100%|##########################################################################################|
Assuming local download is up to date for http://download.geonames.org/export/dump/cities15000.zip
RAM used: 40 MB ETA:   0:00:08 Done:  39%|###################################                                                       |Saving Udaipur, Rajasthan, India failed: IntegrityError('UNIQUE constraint failed: cities_light_city.region_id, cities_light_city.slug')
RAM used: 40 MB ETA:   0:00:12 Done:  39%|###################################                                                       |Saving Tāndā, Uttar Pradesh, India failed: IntegrityError('UNIQUE constraint failed: cities_light_city.region_id, cities_light_city.slug')
RAM used: 40 MB ETA:   0:00:16 Done:  39%|###################################                                                       |Saving Sivagiri, Tamil Nadu, India failed: IntegrityError('UNIQUE constraint failed: cities_light_city.region_id, cities_light_city.slug')
RAM used: 40 MB ETA:   0:00:20 Done:  39%|###################################                                                       |Saving Shamsābād, Uttar Pradesh, India failed: IntegrityError('UNIQUE constraint failed: cities_light_city.region_id, cities_light_city.slug')
RAM used: 40 MB ETA:   0:00:20 Done:  40%|####################################                                                      |Saving Shāhpura, Rajasthan, India failed: IntegrityError('UNIQUE constraint failed: cities_light_city.region_id, cities_light_city.slug')
RAM used: 40 MB ETA:   0:00:20 Done:  40%|####################################                                                      |Saving Shāhābād, Uttar Pradesh, India failed: IntegrityError('UNIQUE constraint failed: cities_light_city.region_id, cities_light_city.slug')
RAM used: 40 MB ETA:   0:00:30 Done:  40%|####################################                                                      |Saving Rāmpur, Uttar Pradesh, India failed: IntegrityError('UNIQUE constraint failed: cities_light_city.region_id, cities_light_city.slug')
RAM used: 40 MB ETA:   0:00:31 Done:  40%|####################################                                                      |Saving Rajpur, Madhya Pradesh, India failed: IntegrityError('UNIQUE constraint failed: cities_light_city.region_id, cities_light_city.slug')
RAM used: 40 MB ETA:   0:00:31 Done:  40%|####################################                                                      |Saving Rājgarh, Rajasthan, India failed: IntegrityError('UNIQUE constraint failed: cities_light_city.region_id, cities_light_city.slug')
Saving Rājgarh, Madhya Pradesh, India failed: IntegrityError('UNIQUE constraint failed: cities_light_city.region_id, cities_light_city.slug')
RAM used: 40 MB ETA:   0:00:33 Done:  41%|####################################                                                      |Traceback (most recent call last):
  File "./manage.py", line 21, in <module>
    main()
  File "./manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/tau/.virtualenvs/shiva/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/tau/.virtualenvs/shiva/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/tau/.virtualenvs/shiva/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/tau/.virtualenvs/shiva/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/home/tau/.virtualenvs/shiva/lib/python3.8/site-packages/cities_light/management/commands/cities_light.py", line 205, in handle
    self.city_import(items)
  File "/home/tau/.virtualenvs/shiva/lib/python3.8/site-packages/cities_light/management/commands/cities_light.py", line 501, in city_import
    subregion_id = self._get_subregion_id(
  File "/home/tau/.virtualenvs/shiva/lib/python3.8/site-packages/cities_light/management/commands/cities_light.py", line 285, in _get_subregion_id
    SubRegion.objects.get(
  File "/home/tau/.virtualenvs/shiva/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tau/.virtualenvs/shiva/lib/python3.8/site-packages/django/db/models/query.py", line 419, in get
    raise self.model.MultipleObjectsReturned(
cities_light.models.MultipleObjectsReturned: get() returned more than one SubRegion -- it returned 2!
(shiva) [tau@archlinux shiva-code]$ 

~~~

**Comment by datacombussys** [comment]
I am having the same issue. Downloads are not working as of yesterday 6-4-20

**Comment by bomba1990** [comment]
@iogf @datacombussys the code from the master branch has the issue resolved, please test and reopen the issue if necessary.
