### ISSUE TITLE
cities_light.City.country: (fields.E304) Reverse accessor for 'City.country' clashes ... etc.

### ISSUE THREAD

**Issue by samdale67** [jazzband/django-cities-light#223]
Hi all,

Attempted to get django-cities-light up and running today, assiduously following documentation. I'm getting the following scary error. Newbie here.

```
ERRORS:
cities_light.City.country: (fields.E304) Reverse accessor for 'City.country' clashes with reverse accessor for 'City.country'.
	HINT: Add or change a related_name argument to the definition for 'City.country' or 'City.country'.
cities_light.City.region: (fields.E304) Reverse accessor for 'City.region' clashes with reverse accessor for 'City.region'.
	HINT: Add or change a related_name argument to the definition for 'City.region' or 'City.region'.
cities_light.City.subregion: (fields.E304) Reverse accessor for 'City.subregion' clashes with reverse accessor for 'City.subregion'.
	HINT: Add or change a related_name argument to the definition for 'City.subregion' or 'City.subregion'.
cities_light.Region.country: (fields.E304) Reverse accessor for 'Region.country' clashes with reverse accessor for 'Region.country'.
	HINT: Add or change a related_name argument to the definition for 'Region.country' or 'Region.country'.
cities_light.SubRegion.country: (fields.E304) Reverse accessor for 'SubRegion.country' clashes with reverse accessor for 'SubRegion.country'.
	HINT: Add or change a related_name argument to the definition for 'SubRegion.country' or 'SubRegion.country'.
cities_light.SubRegion.region: (fields.E304) Reverse accessor for 'SubRegion.region' clashes with reverse accessor for 'SubRegion.region'.
	HINT: Add or change a related_name argument to the definition for 'SubRegion.region' or 'SubRegion.region'.
collections_app.City.country: (fields.E304) Reverse accessor for 'City.country' clashes with reverse accessor for 'City.country'.
	HINT: Add or change a related_name argument to the definition for 'City.country' or 'City.country'.
collections_app.City.region: (fields.E304) Reverse accessor for 'City.region' clashes with reverse accessor for 'City.region'.
	HINT: Add or change a related_name argument to the definition for 'City.region' or 'City.region'.
collections_app.City.subregion: (fields.E304) Reverse accessor for 'City.subregion' clashes with reverse accessor for 'City.subregion'.
	HINT: Add or change a related_name argument to the definition for 'City.subregion' or 'City.subregion'.
collections_app.Region.country: (fields.E304) Reverse accessor for 'Region.country' clashes with reverse accessor for 'Region.country'.
	HINT: Add or change a related_name argument to the definition for 'Region.country' or 'Region.country'.
collections_app.SubRegion.country: (fields.E304) Reverse accessor for 'SubRegion.country' clashes with reverse accessor for 'SubRegion.country'.
	HINT: Add or change a related_name argument to the definition for 'SubRegion.country' or 'SubRegion.country'.
collections_app.SubRegion.region: (fields.E304) Reverse accessor for 'SubRegion.region' clashes with reverse accessor for 'SubRegion.region'.
	HINT: Add or change a related_name argument to the definition for 'SubRegion.region' or 'SubRegion.region'.
```
My settings.py below. 

```
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'collections_app',
    'collectors_app',
    'ckeditor',
    'cities_light',
]

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic'],
            ['NumberedList', 'BulletedList', 'SpecialChar',],
            ['Link', 'Unlink'],
            ['RemoveFormat', 'Source']],
        'height': 250,
        'width': 620,
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'artist_files_directory.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates', 'collections_app/templates/collections_app', 'collectors_app/templates'
                                                                           '/collectors_app'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'collections_app.context_processors.last_database_update',
                'collections_app.context_processors.navigation_content'
            ],
        },
    },
]

WSGI_APPLICATION = 'artist_files_directory.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'artist_files_directory',
        'USER': 'afd_master',
        'PASSWORD':
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'static')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'), ]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_REDIRECT_URL = "/user/content/"
LOGOUT_REDIRECT_URL = "/"

CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"

EMAIL_HOST = 'localhost'
EMAIL_PORT = 1025

CITIES_LIGHT_TRANSLATION_LANGUAGES = ['es', 'en', 'fr', 'abbr']
CITIES_LIGHT_INCLUDE_COUNTRIES = ['CA', 'MX', 'US']
CITIES_LIGHT_INCLUDE_CITY_TYPES = ['PPL', 'PPLA', 'PPLA2', 'PPLA3', 'PPLA4', 'PPLC', 'PPLF', 'PPLG', 'PPLL',
                                   'PPLR', 'PPLS', 'STLMT']
```

Related models.py

```
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User
from cities_light.abstract_models import (AbstractCity, AbstractRegion, AbstractSubRegion,
                                          AbstractCountry)
from cities_light.receivers import connect_default_signals
from ckeditor.fields import RichTextField


class Country(AbstractCountry):
    pass


connect_default_signals(Country)


class Region(AbstractRegion):
    pass


connect_default_signals(Region)


class SubRegion(AbstractSubRegion):
    pass


connect_default_signals(SubRegion)


class City(AbstractCity):
    modification_date = models.CharField(max_length=40)


connect_default_signals(City)


class Collection(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    state_province = models.ForeignKey(Region, on_delete=models.CASCADE)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
```

**Comment by samdale67** [comment]
Hi all,

Well, I think I've got it figured out, and I think it's the coolest thing EVER. A round of applause to the developers.

That said, in my case I'm only doing Canada, Mexico, and U.S., and it seems I only have Canadian cities downloading. It's this a known issue or something I've done wrong?

I can report the following error:

```
File "/Users/samduncan/Dev/artist-files-directory/lib/python3.8/site-packages/django/db/models/query.py", line 419, in get
    raise self.model.MultipleObjectsReturned(
cities_light.models.MultipleObjectsReturned: get() returned more than one SubRegion -- it returned 20!
```
![2020-07-13_capture-01](https://user-images.githubusercontent.com/63515650/87365262-66672700-c53b-11ea-9751-07e98d45e7ae.jpg)

**Comment by bomba1990** [comment]
@samdale67 
This error is already solved on the máster branch. Please install using the following command:

`pip install git+https://github.com/jazzband/django-cities-light.git`

**Comment by samdale67** [comment]
Hi there, and thanks.

I installed and ran " python3 manage.py cities_light" to populate database. Here's what I got. Did I do something wrong?

```
(artist-files-directory) $ pip3 install git+https://github.com/jazzband/django-cities-light.git
Collecting git+https://github.com/jazzband/django-cities-light.git
  Cloning https://github.com/jazzband/django-cities-light.git to /private/var/folders/97/2pszp8vx6hj2q9322nnc5ptc0000gp/T/pip-req-build-b86odsu4
  Running command git clone -q https://github.com/jazzband/django-cities-light.git /private/var/folders/97/2pszp8vx6hj2q9322nnc5ptc0000gp/T/pip-req-build-b86odsu4
Requirement already satisfied (use --upgrade to upgrade): django-cities-light==3.6.0 from git+https://github.com/jazzband/django-cities-light.git in ./lib/python3.8/site-packages
Requirement already satisfied: six in ./lib/python3.8/site-packages (from django-cities-light==3.6.0) (1.15.0)
Requirement already satisfied: pytz in ./lib/python3.8/site-packages (from django-cities-light==3.6.0) (2020.1)
Requirement already satisfied: unidecode>=0.04.13 in ./lib/python3.8/site-packages (from django-cities-light==3.6.0) (1.1.1)
Collecting django-autoslug-iplweb>=1.9.4
  Downloading django_autoslug_iplweb-1.9.5-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: progressbar2>=3.6.0 in ./lib/python3.8/site-packages (from django-cities-light==3.6.0) (3.51.4)
Requirement already satisfied: python-utils>=2.3.0 in ./lib/python3.8/site-packages (from progressbar2>=3.6.0->django-cities-light==3.6.0) (2.4.0)
Building wheels for collected packages: django-cities-light
  Building wheel for django-cities-light (setup.py) ... done
  Created wheel for django-cities-light: filename=django_cities_light-3.6.0-py3-none-any.whl size=45960 sha256=713beb806f741e7bb9817fa7f4b89007a4ef9a6e3404a588a26d3468a43a8b36
  Stored in directory: /private/var/folders/97/2pszp8vx6hj2q9322nnc5ptc0000gp/T/pip-ephem-wheel-cache-adz8to6p/wheels/9b/11/86/5ed21f8e48e239cb4abe3ed2fd3d6a920a8b703b366f1d9ddb
Successfully built django-cities-light
ERROR: django-cities-light 3.6.0 has requirement django-autoslug-iplweb==1.9.4.dev0, but you'll have django-autoslug-iplweb 1.9.5 which is incompatible.
Installing collected packages: django-autoslug-iplweb
  Attempting uninstall: django-autoslug-iplweb
    Found existing installation: django-autoslug-iplweb 1.9.4.dev0
    Uninstalling django-autoslug-iplweb-1.9.4.dev0:
      Successfully uninstalled django-autoslug-iplweb-1.9.4.dev0
Successfully installed django-autoslug-iplweb-1.9.5
(artist-files-directory) $ python3 manage.py cities_light
Saving Sainte-Catherine, Quebec, Canada failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_name_29b81cd4_uniq"\nDETAIL:  Key (region_id, name)=(10, Sainte-Catherine) already exists.\n')
Saving Vernon, British Columbia, Canada failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_name_29b81cd4_uniq"\nDETAIL:  Key (region_id, name)=(2, Vernon) already exists.\n')
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Users/samduncan/Dev/artist-files-directory/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/samduncan/Dev/artist-files-directory/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/samduncan/Dev/artist-files-directory/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/samduncan/Dev/artist-files-directory/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/Users/samduncan/Dev/artist-files-directory/lib/python3.8/site-packages/cities_light/management/commands/cities_light.py", line 205, in handle
    self.city_import(items)
  File "/Users/samduncan/Dev/artist-files-directory/lib/python3.8/site-packages/cities_light/management/commands/cities_light.py", line 501, in city_import
    subregion_id = self._get_subregion_id(
  File "/Users/samduncan/Dev/artist-files-directory/lib/python3.8/site-packages/cities_light/management/commands/cities_light.py", line 285, in _get_subregion_id
    SubRegion.objects.get(
  File "/Users/samduncan/Dev/artist-files-directory/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/samduncan/Dev/artist-files-directory/lib/python3.8/site-packages/django/db/models/query.py", line 419, in get
    raise self.model.MultipleObjectsReturned(
cities_light.models.MultipleObjectsReturned: get() returned more than one SubRegion -- it returned 20
```!

**Comment by samdale67** [comment]
So I still only see Canadian cities, nothing from U.S. or Mexico.

**Comment by samdale67** [comment]
Hi all, is this something I can fix on my end? Would be happy to do whatever I need to do in order to fix. I feel this is so close to working! Thanks again!

**Comment by bomba1990** [comment]
@samdale67 First, Try to uninstall the previous version of django-cities-light. And then try again.

**Comment by samdale67** [comment]
Howdy from Texas. Could you help a newbie with the command to uninstall? I've never done an uninstall. Thanks.

**Comment by bomba1990** [comment]
pip uninstall django-cities-light

**Comment by samdale67** [comment]
It's working beautifully. Thanks so much for your hand holding. Best from Texas!
