### ISSUE TITLE
Migrate issue on Django==3.1

### ISSUE THREAD

**Issue by dphans** [jazzband/django-cities-light#231]
Package dependencies:
Django==3.1
django-cities-light==3.6.0

Steps:
1. Install django-cities-light==3.6.0 via pip.
2. Add `cities_light` into `INSTALLED_APPS`.
3. Run migrate `python3 manage.py migrate`.

Result:

```bash
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/cities_light/models.py", line 83, in <module>
    from .abstract_models import (AbstractCountry, AbstractRegion,
  File "/usr/local/lib/python3.8/site-packages/cities_light/abstract_models.py", line 5, in <module>
    import autoslug
  File "/usr/local/lib/python3.8/site-packages/autoslug/__init__.py", line 11, in <module>
    from autoslug.fields import AutoSlugField
  File "/usr/local/lib/python3.8/site-packages/autoslug/fields.py", line 29, in <module>
    from autoslug.settings import slugify, autoslug_modeltranslation_enable
  File "/usr/local/lib/python3.8/site-packages/autoslug/settings.py", line 68, in <module>
    slugify = get_callable(slugify_function_path)
  File "/usr/local/lib/python3.8/site-packages/django/urls/utils.py", line 28, in get_callable
    mod = import_module(mod_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.8/site-packages/autoslug/utils.py", line 15, in <module>
    from django.db.models.fields import FieldDoesNotExist, DateField
ImportError: cannot import name 'FieldDoesNotExist' from 'django.db.models.fields' (/usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py)
```

I think the correct import `FieldDoesNotExist` in library must be:
```
from django.core.exceptions import FieldDoesNotExist

```

**Comment by marianoeramirez** [comment]
@dphans This error is already solved on the máster branch. Please test and let us now.

**Comment by dphans** [comment]
Very quickly! Thank you!
